# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: CmdLine@2
  inputs:
    script: 'chmod 777 gradlew'
- task: CmdLine@2
  inputs:
    script: 'ls -l'
#- task: Gradle@3
#  inputs:
#    gradleWrapperFile: 'gradlew'
#    tasks: 'clean'
#    publishJUnitResults: true
#    testResultsFiles: '**/TEST-*.xml'
#    testRunTitle: 'libery-test'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.11'
#    sonarQubeRunAnalysis: false
#    spotBugsAnalysis: false    
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
